### ISSUE TITLE
Is it possible to provide video tutorials?

### ISSUE THREAD

**Issue by ZhoucpSAMA** [JPShag/DMA-FW-Guide-2.0#1]
I'm a java programmer, recently I'm learning to make emulation DMA firmware related knowledge, thank you very much for providing document tutorials, but it's still a little difficult to learn, not good at English.

**Comment by JPShag** [comment]
Potentially. Add me on discord **vcpu**
I have a few questions I want to run by you

**Comment by JPShag** [comment]
I will close this. I want to make tutorials, but I don't havr the time right now, money is tight for me so I must focus on working. If things change I will happily provide these videos.

**Comment by ZhoucpSAMA** [comment]
As far as I know, many Chinese use this and you can make money from them through this.
